export const IMAGES = [
    {
        img: "https://movies-b26f.kxcdn.com/wp-content/uploads/2014/09/PorcoRosso7.jpg",
        e:"🎂 ",
        lbl: " birthday cake ",
        quote:  "Wishing you a day filled with happiness & laughter. Happy birthday, dear friend!",
        attr: "✨ happy birthday ✨ ",
    },
     {
        img: "https://images.theskinny.co.uk/assets/production/000/143/870/143870_widescreen.jpg",
        e:"🍈 ",
        lbl: "kinda melon",
        quote: "Wishing you a lifetime of thinking about me hehe 😄 ",
        attr: "🎊 celebrate you 🎊 ",
    },
     {
        img: "https://www.bam.org/globalassets/programs/cinema/2026fy/0825/tragedy-then-farce/porco-rosso-1992__2.jpeg?width=1920&mode=crop&heightratio=0.5625&quality=80",
        e:" 🎁",
         lbl: "gift box",
        quote: " You are the greatest gift to everyone who knows you.",
        attr: "🎀 you're a gift 🎀 ",
    },
     {
        img: "https://www.cinematheque.qc.ca/workspace/uploads/projections/boqc0hx8gtuhgybhp9o6nqwzrz8-fr-1742482399.jpg",
        e:"🍎 ",
         lbl: "cambodia apple",
        quote: " Friends are the sunshine of life.",
        attr: "— John Hay ",
    },
     {
        img: "https://m.media-amazon.com/images/M/MV5BNTg1MzM5NDMxN15BMl5BanBnXkFtZTgwMTYyMDk2MjE@._V1_.jpg",
        e:" 🌶️",
         lbl: "chili for neighbors",
        quote: "A real friend walks in when the rest of the world walks out. ",
        attr: " — Walter Winchell",
    },
     {
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGHPTj7mPeibmwALwhmq1V5r0ikPSHQEOPTQ&s",
        e:" 🌿",
         lbl: "garden chili",
        quote: " Friendship is born at the moment one person says: 'What! You too?'",
        attr: "— C.S. Lewis ",
    },
     {
        img: "https://static0.cbrimages.com/wordpress/wp-content/uploads/2025/02/custom-image-of-studio-ghibli-s-porco-rosso.jpg?w=1600&h=900&fit=crop",
        e:"🌻 ",
         lbl: "sunflower",
        quote: "Good friends are like stars — you don't always see them but you know they're there. ",
        attr: "— Unknown ",
    },
     {
        img: "gal8.jpg",
        e:"😂 ",
         lbl: "Laughing",
        quote: "A friend is someone who makes it easy to believe in yourself. ",
        attr: " — Heidi Wills",
    },
     {
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh8xNOo7_n0YXfcfPd7n9zW0fQoApZsZ7TnQ&s",
        e:" 💐",
         lbl: "bouquet",
        quote: " A friend hears the song in my heart and sings it when my memory fails.",
        attr: " — Unknown",
    },
     {
        img: "https://images.squarespace-cdn.com/content/v1/5a90557e1137a6fdeeb6bb3e/1608809886788-86E4JUW3QBF50678J7R1/Porco_Rosso_963064296_large.0.jpg",
        e:"🦋 ",
         lbl: "butterfly",
        quote: "Friends show their love in times of trouble, not just in times of happiness. ",
        attr: " — Euripides",
    },
];